// project/src/views/Home/Home.tsx
import React, {
  useEffect,
} from 'react';
import { withRouter } from 'react-router-dom';
import { Board } from '@/components/Board/Board';
import { ToolBar } from '@/components/ToolBar/ToolBar';

const Home: React.FC = () => {
  useEffect(() => {
    document.title = '画板';
  });

  return (
    <div>
      <Board />
      <ToolBar />
    </div>
  );
};

export default withRouter(Home);

// project-vue/src/pages/Home.vue
<template>
	<div class="home">
		<Toolbar />
		<Board />
	</div>
</template>

<script>
import Board from '../components/board/Board.vue';
import Toolbar from '../components/toolbar/Toolbar.vue';

export default {
	components: {
		Board,
		Toolbar,
	},
};
</script>

<style lang="less" scoped>
.home {
	position: relative;
}
</style>
